# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'BaiSiBuDeJie' do

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking'
pod 'MJExtension'
pod 'YYImage'
pod 'YYImage/WebP'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'LookinServer', :configurations => ['Debug']

end
