# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaiSiBuDeJie' do

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking'
pod 'MJExtension'

end
